import {
	boolean,
	integer,
	jsonb,
	numeric,
	pgTable,
	serial,
	smallint,
	varchar,
} from "drizzle-orm/pg-core";

export const pokemons = pgTable("pokemons", {
	id: serial("id").primaryKey(),
	dexNumber: integer("dex_number").notNull(),
	name: varchar("name", { length: 100 }).notNull().unique(),
	formName: varchar("form_name", { length: 100 }),
	isDefault: boolean("is_default").notNull().default(true),
	isMega: boolean("is_mega").notNull().default(false),
	apiId: integer("api_id").notNull().unique(),
	imageUrl: varchar("image_url", { length: 500 }),
	hp: smallint("hp").notNull(),
	attack: smallint("attack").notNull(),
	defense: smallint("defense").notNull(),
	spAttack: smallint("sp_attack").notNull(),
	spDefense: smallint("sp_defense").notNull(),
	speed: smallint("speed").notNull(),
	weight: numeric("weight").notNull(),
	height: numeric("height").notNull(),
	typeIds: jsonb("type_ids").$type<number[]>().notNull().default([]),
	abilityIds: jsonb("ability_ids").$type<number[]>().notNull().default([]),
	moveIds: jsonb("move_ids").$type<number[]>().notNull().default([]),
});
